services:
  # PostgreSQL Database (Disabled - using external database)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: portfolio_postgres
  #   environment:
  #     POSTGRES_DB: portfolio_db
  #     POSTGRES_USER: portfolio_user
  #     POSTGRES_PASSWORD: portfolio_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - portfolio_network
  #   restart: unless-stopped

  # Portfolio Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    environment:
      - NODE_ENV=production
      - PORT=5000
    secrets:
      - database_url
      - session_secret
    ports:
      - "5000:5000"
    networks:
      - portfolio_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - portfolio_network
    restart: unless-stopped

networks:
  portfolio_network:
    driver: bridge

secrets:
  database_url:
    external: true
    name: /my_showcase/database_url
  session_secret:
    external: true
    name: /my_showcase/session_secret 