version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres_dev
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - portfolio_network_dev
    restart: unless-stopped

  # Portfolio Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio_app_dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://portfolio_user:portfolio_password@postgres:5432/portfolio_db
      - SESSION_SECRET=dev_session_secret
    ports:
      - "5000:5000"
      - "5173:5173"  # Vite dev server
    depends_on:
      - postgres
    networks:
      - portfolio_network_dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist

volumes:
  postgres_data_dev:

networks:
  portfolio_network_dev:
    driver: bridge 